version: '3.8'
services:
  homepedia-back:
    container_name: sasia-back
    image: ghcr.io/dinahworld/homepedia-back:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - sasia-bdd
  homepedia-bdd:
    container_name: homepedia
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: admin
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata: