name: Update VM

on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Update Docker Compose
        run: |
          docker-compose down && docker-compose pull sasia-back && docker-compose up -d